export default {
  name: 'gmail-priority',
  type: 'worker',
  runtime: 'lambda',
  direction: 'INBOUND',
  triggers: ['manual', 'schedule', 'webhook'],
  logging: {
    direction: 'INBOUND',
    reviewRequired: true,
    cloudWatchLogGroup: '/automation/integrations/gmail-priority',
    steps: ['Received from Gmail', 'Mapped Gmail quote request', 'Sent to Priority', 'Received from Priority'],
  },
  testing: {
    defaultMode: 'test',
    modes: ['test', 'dry_run', 'live'],
    modeDescriptions: {
      test: 'Runs the worker with local fixture data and mocked provider clients.',
      dry_run: 'Validates mapping and reports the Priority request without creating a live quote.',
      live: 'Uses saved live credentials and may call Gmail and Priority.',
    },
  },
  deployment: {
    pipelineName: 'integration-gmail-priority',
    queueName: 'gmail-priority-queue',
    dlqName: 'gmail-priority-dlq',
    cloudWatchLogGroup: '/automation/integrations/gmail-priority',
  },
  credentials: [
    { key: 'GOOGLE_CLIENT_ID', label: 'Google OAuth Client ID', type: 'secret', helper: 'OAuth client ID from the same Google Cloud OAuth client as the secret.' },
    { key: 'GOOGLE_CLIENT_SECRET', label: 'Google OAuth Client Secret', type: 'secret', helper: 'OAuth client secret from Google Cloud. Never paste it into logs or screenshots.' },
    { key: 'GOOGLE_REFRESH_TOKEN', label: 'Google Refresh Token', type: 'secret', helper: 'Refresh token generated by the local Gmail token helper.' },
    { key: 'PRIORITY_BASE_URL', label: 'Priority API Base URL', type: 'url', helper: 'Base URL for the target Priority API environment.' },
  ],
  sampleJob: 'fixtures/sample-job.json',
};
