import test from 'node:test';
import assert from 'node:assert/strict';
import { handler } from '../src/handler.js';
import definition from '../../../src/integrations/tuf1/priority-delivery-whatsapp/integration.js';
const credentials={ITC_TEMPLATE_MESSAGE_URL:definition.credentials[0].defaultValue,ITC_BEARER_TOKEN:'test-token-not-a-secret',ITC_CHANNEL_ID:'whatsapp:+97246960480'};
const base={ORDNAME:'1597873',CURDATE:'27.07.2026',YARD_CUSTDES:'ירדן',YARD_PHONENUM:'0502009253',YARD_NAME:'שני',YARD_FAX:'+972502009254'};
function context(calls, status=200) { return {config:{credentials},logger:{info(){}},priorityClient:{generateSalesOrderPrintUrl(){throw Error('Web SDK must not run');}},fetchImpl:async(url,options)=>{calls.push({url,options,body:JSON.parse(options.body)});return {ok:status===200,status,text:async()=>JSON.stringify({id:'message-'+calls.length})};}}; }
for(const [label,fields,count] of [ ['both',{},2],['first only',{YARD_NAME:''},1],['second only',{YARD_CUSTDES:''},1],['neither',{YARD_PHONENUM:' ',YARD_FAX:''},0] ]) {
 test(label+' sends only eligible contacts',async()=>{const calls=[];const result=await handler({mode:'live',payload:{DOCUMENTS_D:{...base,...fields}}},context(calls));assert.equal(calls.length,count);assert.equal(result.counts.messagesSent,count);for(const call of calls){assert.equal(call.url,credentials.ITC_TEMPLATE_MESSAGE_URL);assert.deepEqual(Object.keys(call.body),['clientName','msgType','channelId','variables']);assert.equal(call.body.variables.length,3);assert.equal(call.body.variables[1].text,base.ORDNAME);assert.equal(call.body.variables[2].text,base.CURDATE);assert.equal(call.body.msgType,'whatsapp');assert.equal(call.body.channelId,credentials.ITC_CHANNEL_ID);}if(label==='both'){assert.deepEqual(calls.map(x=>x.body.clientName),['+972502009253','+972502009254']);assert.deepEqual(calls.map(x=>x.body.variables[0].text),['ירדן','שני']);}if(label==='second only')assert.equal(calls[0].body.variables[0].text,'שני');});
}
for(const date of ['2026-07-27T00:00:00+03:00',' 27/07/26 ','/Date(1785110400000)/']) test('preserves date text '+date,async()=>{const calls=[];await handler({mode:'live',payload:{DOCUMENTS_D:{...base,CURDATE:date}}},context(calls));assert.equal(calls[0].body.variables[2].text,date);});
for(const mode of ['dry_run','test','mock_output']) test(mode+' does not call a provider',async()=>{const calls=[];const result=await handler({mode,payload:{DOCUMENTS_D:base}},context(calls));assert.equal(calls.length,0);assert.equal(result.success,true);assert.ok(result.additionalRequestSummary);});
test('first provider failure prevents second call',async()=>{const calls=[];await assert.rejects(handler({mode:'live',payload:{DOCUMENTS_D:base}},context(calls,400)),/HTTP 400/);assert.equal(calls.length,1);});
test('rejects wrong input object and invalid telephone',async()=>{const calls=[];await assert.rejects(handler({mode:'live',payload:{ORDERS:base}},context(calls)),/DOCUMENTS_D/);await assert.rejects(handler({mode:'live',payload:{DOCUMENTS_D:{...base,YARD_PHONENUM:'invalid'}}},context(calls)),/phone number/);assert.equal(calls.length,0);});
