const definition = require('./integration');

function safeTimestamp(date = new Date()) {
  return date.toISOString().replace(/[:.]/g, '-');
}

function parseRecipients(value) {
  return String(value || '')
    .split(/[;,\n]/)
    .map((item) => item.trim())
    .filter(Boolean);
}

function resolveEmailProvider(credentials) {
  const provider = String(credentials.EMAIL_PROVIDER || process.env.EMAIL_PROVIDER || 'ses').toLowerCase();
  if (!['ses', 'gmail'].includes(provider)) {
    throw new Error(`Unsupported EMAIL_PROVIDER: ${provider}. Use "ses" or "gmail".`);
  }
  return provider;
}

function buildDocument({ executionMode, credentials, inventoryResult }) {
  const provider = resolveEmailProvider(credentials);
  return {
    generatedAt: new Date().toISOString(),
    integration: 'priority-inventory-to-email',
    executionMode,
    source: {
      system: 'Priority ERP',
      endpoint: executionMode === 'email_test' ? 'embedded dummy inventory' : credentials.PRIORITY_INVENTORY_URL,
      method: executionMode === 'email_test' ? null : 'GET',
      requestBody: null,
    },
    delivery: {
      system: provider === 'ses' ? 'Amazon SES' : 'Gmail API',
      recipients: parseRecipients(credentials.EMAIL_TO_GROUP),
    },
    inventory: inventoryResult.items || [],
    raw: inventoryResult.raw || inventoryResult,
  };
}

function buildSubject(credentials, executionMode) {
  const prefix = credentials.EMAIL_SUBJECT_PREFIX || 'Priority inventory';
  const modeLabel = executionMode === 'email_test' ? 'TEST' : 'LIVE';
  return `${prefix} - ${modeLabel} - ${new Date().toISOString()}`;
}

function buildBody({ document, executionMode }) {
  const lines = [
    executionMode === 'email_test'
      ? 'This is a test email generated by the Priority inventory to email integration.'
      : 'Priority inventory export is attached as JSON.',
    '',
    `Generated at: ${document.generatedAt}`,
    `Execution mode: ${executionMode}`,
    `Inventory rows: ${document.inventory.length}`,
    '',
    'The full JSON payload is attached to this email.',
  ];
  return lines.join('\n');
}

module.exports = {
  async execute({ credentials, logger, connectors, executionMode }) {
    await logger.info('Priority inventory to email started.', { executionMode });

    const recipients = parseRecipients(credentials.EMAIL_TO_GROUP);
    if (recipients.length === 0) throw new Error('EMAIL_TO_GROUP must contain at least one recipient email address.');

    let inventoryResult;
    if (executionMode === 'email_test') {
      inventoryResult = {
        success: true,
        mocked: true,
        items: definition.sampleData.inventory,
        raw: { value: definition.sampleData.inventory },
      };
      await logger.info('Using embedded dummy Priority inventory for email test.', { itemCount: inventoryResult.items.length });
    } else if (executionMode === 'live') {
      inventoryResult = await connectors.priority.getInventory({
        requestBody: undefined,
        endpointUrl: credentials.PRIORITY_INVENTORY_URL,
      });
      await logger.info('Priority inventory retrieved for email delivery.', { itemCount: (inventoryResult.items || []).length });
    } else {
      throw new Error(`Unsupported execution mode for this integration: ${executionMode}`);
    }

    const emailProvider = resolveEmailProvider(credentials);
    const document = buildDocument({ executionMode, credentials, inventoryResult });
    const timestamp = safeTimestamp();
    const filename = `priority-inventory-${executionMode}-${timestamp}.json`;
    const subject = buildSubject(credentials, executionMode);
    const text = buildBody({ document, executionMode });

    const emailConnector = emailProvider === 'ses' ? connectors.ses : connectors.gmail;
    const emailResult = await emailConnector.sendEmail({
      to: recipients,
      subject,
      text,
      attachments: [
        {
          filename,
          contentType: 'application/json',
          content: JSON.stringify(document, null, 2),
        },
      ],
    });

    await logger.info('Priority inventory email sent.', {
      recipientCount: recipients.length,
      itemCount: document.inventory.length,
      attachment: filename,
      mockedInventory: inventoryResult.mocked === true,
      provider: emailResult.provider || emailProvider,
    });

    return {
      success: true,
      emailed: true,
      recipientCount: recipients.length,
      itemCount: document.inventory.length,
      attachment: filename,
      mockedInventory: inventoryResult.mocked === true,
      provider: emailResult.provider || emailProvider,
    };
  },
  _diagnostics: { parseRecipients, resolveEmailProvider, buildDocument },
};
