module.exports = {
  name: 'Priority Order Notification via ITC',
  displayName: 'Priority Order Notification via ITC',
  integrationKey: 'tuf1-priority-order-itc',
  version: '1.5.3',
  description: 'Receives a Priority customer-order webhook, generates its sales-order confirmation with Priority Web SDK, saves a server copy, and sends the server URL in an ITC WhatsApp template message.',
  type: 'webhook',
  direction: 'OUTBOUND',
  runtime: 'lambda',
  triggers: ['webhook', 'manual'],
  manualRun: true,

  connectors: ['priorityWebSdk', 'itc'],
  credentialTests: ['priorityWebSdk', 'itc'],
  webhook: {
    method: 'POST',
    requiresToken: true,
  },

  logging: {
    direction: 'OUTBOUND',
    reviewRequired: true,
    cloudWatchLogGroup: '/aws/lambda/priority-order-itc',
    steps: [
      'Execution started',
      'Received from Priority: customer order JSON',
      'Sent to Priority: WWWSHOWORDER sales order confirmation request',
      'Received from Priority: sales order confirmation URL',
      'Stored Priority document copy on automation server',
      'Stored provider delivery in-flight marker',
      'Sent to ITC: template message JSON',
      'Received from ITC: template message response',
      'Stored finalization state',
      'Updated dashboard execution status',
      'Execution finished',
    ],
  },

  testing: {
    allowManualPayload: true,
    allowDryRun: true,
    allowMockOutput: true,
    allowReplay: true,
    defaultMode: 'dry_run',
    modes: ['dry_run', 'test', 'mock_output', 'live'],
    modeDescriptions: {
      dry_run: 'Validates and maps the Priority order, uses a mock sales-order confirmation URL, and shows a redacted ITC request without calling Priority or ITC.',
      test: 'Builds the ITC request with a mock Priority confirmation URL. It does not log in to Priority or send an ITC message.',
      mock_output: 'Uses a mock Priority confirmation URL and a mock accepted ITC response. No external system is called.',
      live: 'Logs in with Priority Web SDK, runs WWWSHOWORDER for ORDERS.ORDNAME with print format -109, saves the document on the automation server, then sends the server URL as ITC variable 3 in a real message.',
    },
  },

  credentials: [
    {
      key: 'ITC_TEMPLATE_MESSAGE_URL',
      label: 'ITC Template Message URL',
      type: 'text',
      required: true,
      defaultValue: 'https://sv1.effective-oc.com/api/v2/msg/sendMsg/tempMsg/6a4b93a55c44e81728f3dc89',
      helper: 'Full ITC POST endpoint for this approved template, including the template ID at the end of the URL.',
      helperUrl: 'https://effective-oc.com/',
      helperUrlLabel: 'Open the Effective/ITC portal',
      placeholder: 'https://sv1.effective-oc.com/api/v2/msg/sendMsg/tempMsg/<template-id>',
      validation: { pattern: '^https://.+' },
    },
    {
      key: 'ITC_BEARER_TOKEN',
      label: 'ITC Bearer Token',
      type: 'secret',
      required: true,
      masked: true,
      helper: 'Bearer token supplied by ITC. It is stored securely, masked after saving, and never included in logs or API responses.',
      helperUrl: 'https://effective-oc.com/',
      helperUrlLabel: 'Open the Effective/ITC portal',
      placeholder: 'Paste a rotated ITC bearer token',
      validation: { minLength: 20 },
    },
    {
      key: 'ITC_CHANNEL_ID',
      label: 'ITC Channel ID',
      type: 'text',
      required: true,
      defaultValue: 'whatsapp:+97246960480',
      helper: 'ITC WhatsApp sending channel in the format whatsapp:+<country-code><number>.',
      helperUrl: 'https://effective-oc.com/',
      helperUrlLabel: 'Find the channel in the Effective/ITC portal',
      placeholder: 'whatsapp:+97246960480',
      validation: { pattern: '^whatsapp:\\+[0-9]{8,15}$' },
    },
    {
      key: 'PRIORITY_WEB_SDK_URL',
      label: 'Priority Web SDK URL',
      type: 'url',
      required: true,
      helper: 'Copy the HTTPS WCF Service.svc URL from automation cmqwxeyem00019hv5q0mbml0g, or ask your Priority administrator for the Web SDK service URL.',
      placeholder: 'https://priority.example.com/wcf/wcf/Service.svc',
      validation: { pattern: '^https://.+' },
    },
    {
      key: 'PRIORITY_WEB_SDK_TABULAINI',
      label: 'Priority tabula.ini',
      type: 'text',
      required: true,
      defaultValue: 'tabula.ini',
      helper: 'Copy the ini filename from the existing Priority Web SDK connection, or ask your Priority administrator. The usual value is tabula.ini.',
      placeholder: 'tabula.ini',
    },
    {
      key: 'PRIORITY_WEB_SDK_LANGUAGE',
      label: 'Priority Language',
      type: 'number',
      required: true,
      defaultValue: 3,
      helper: 'Ask your Priority administrator for the Web SDK language number. The provided English example uses 3; it must match the translated Order Sort Option below.',
      placeholder: '3',
    },
    {
      key: 'PRIORITY_WEB_SDK_COMPANY',
      label: 'Priority Company',
      type: 'text',
      required: true,
      helper: 'Copy profile.company from the existing Priority Web SDK connection, or ask your Priority administrator for the company/environment code.',
      placeholder: 'demo',
    },
    {
      key: 'PRIORITY_WEB_SDK_APPNAME',
      label: 'Priority App Name',
      type: 'text',
      required: true,
      helper: 'Copy the app name from the existing Priority Web SDK connection, or ask your Priority administrator for the application name assigned to this integration.',
      placeholder: 'demo',
    },
    {
      key: 'PRIORITY_WEB_SDK_USERNAME',
      label: 'Priority Username',
      type: 'text',
      required: true,
      helper: 'Ask your Priority administrator for the service username that is allowed to run WWWSHOWORDER.',
      placeholder: 'api.user',
    },
    {
      key: 'PRIORITY_WEB_SDK_PASSWORD',
      label: 'Priority Password',
      type: 'secret',
      required: true,
      masked: true,
      helper: 'Get the password for the WWWSHOWORDER service user from your Priority administrator. It is stored securely, masked after saving, and never returned or logged.',
      placeholder: 'Paste the Priority password',
    },
    {
      key: 'PRIORITY_WEB_SDK_DEVICENAME',
      label: 'Priority Device Name',
      type: 'text',
      required: false,
      helper: 'Ask your Priority administrator whether the Web SDK login requires a device name. Leave blank when it does not.',
      placeholder: 'Optional',
    },
    {
      key: 'PRIORITY_WEB_SDK_ORDER_SORT_OPTION',
      label: 'Order Sort Option',
      type: 'text',
      required: true,
      defaultValue: 'By Order Number',
      helper: 'The desired WWWSHOWORDER Sort choice. The default selects Priority’s first “By Order Number” choice even when the session displays it in another language. Enter another choice exactly as Priority displays it.',
      placeholder: 'By Order Number',
    },
  ],

  deployment: {
    pipelineName: 'integration-priority-order-itc',
    lambdaName: 'priority-order-itc',
    queueName: 'priority-order-itc-queue',
    dlqName: 'priority-order-itc-dlq',
    cloudWatchLogGroup: '/aws/lambda/priority-order-itc',
    independentPipelineRequired: true,
    apiMustNotRestart: true,
    queueRequired: true,
    dlqRequired: true,
    scheduleRequired: false,
    batchSize: 1,
    reportBatchItemFailures: true,
    timeoutSeconds: 60,
    logRetentionDays: 30,
    credentialSource: 'dashboard-settings-and-secrets-manager-references',
    workerStatusCallbackRequired: true,
    finalizationTableName: 'priority-order-itc-finalization',
    idempotencyStrategy: 'durable-in-flight-marker-before-itc-and-finalization-before-status-callback',
  },

  uiux: {
    reviewRequired: true,
    credentialSectionTitle: 'ITC settings',
    showSavedSecretPlaceholder: true,
    savedSecretPlaceholder: '•••••••• saved',
    requireConnectionTestButton: true,
    requireRunTestButton: true,
    requireHelperText: true,
  },

  privacy: {
    executionPayloadAllowlistPaths: [
      'ORDERS.ORDNAME',
      'ORDERS.ZANA_CUSTDES',
      'ORDERS.ZANA_PHONENUM',
    ],
    executionPayloadRedactionPaths: [
      'ORDERS.ORDNAME',
      'ORDERS.ZANA_PHONENUM',
    ],
  },

  testPayloads: [
    {
      name: 'Priority customer order',
      description: 'Maps ZANA_CUSTDES to variable 1 and WWWSHOWORDER input, ORDNAME to variable 2, the generated confirmation URL to variable 3, and ZANA_PHONENUM to the ITC recipient.',
      payload: {
        ORDERS: {
          ORDNAME: 'SO26000001',
          ZANA_CUSTDES: 'ירדן',
          ZANA_PHONENUM: '+972507573753',
        },
      },
    },
  ],
};
