export default {
  name: 'priority-order-itc',
  displayName: 'Priority Customer Order to ITC',
  version: '1.5.2',
  type: 'worker',
  runtime: 'lambda',
  direction: 'OUTBOUND',
  triggers: ['webhook', 'manual', 'queue'],
  connectors: ['priorityWebSdk', 'itc'],
  credentialTests: ['priorityWebSdk', 'itc'],
  logging: {
    direction: 'OUTBOUND',
    reviewRequired: true,
    cloudWatchLogGroup: '/aws/lambda/priority-order-itc',
    steps: ['Execution started', 'Received from Priority', 'Sent to Priority Web SDK', 'Received from Priority Web SDK', 'Stored provider delivery in-flight marker', 'Sent to ITC', 'Received from ITC', 'Stored finalization state', 'Updated dashboard execution status', 'Execution finished'],
  },
  testing: {
    defaultMode: 'dry_run',
    modes: ['dry_run', 'test', 'mock_output', 'live'],
    modeDescriptions: {
      dry_run: 'Validates and maps the order with a mock Priority confirmation URL and does not call Priority or ITC.',
      test: 'Uses fixture input and prepares a sanitized ITC request with a mock Priority confirmation URL.',
      mock_output: 'Uses mock Priority and ITC output without making an external request.',
      live: 'Runs Priority WWWSHOWORDER for ORDERS.ORDNAME with print format -109, saves the document on the automation server, and posts the server URL to ITC as variable 3.',
    },
  },
  deployment: {
    pipelineName: 'integration-priority-order-itc',
    queueName: 'priority-order-itc-queue',
    dlqName: 'priority-order-itc-dlq',
    cloudWatchLogGroup: '/aws/lambda/priority-order-itc',
    lambdaName: 'priority-order-itc',
    batchSize: 1,
    reportBatchItemFailures: true,
    timeoutSeconds: 60,
    logRetentionDays: 30,
    credentialSource: 'dashboard-settings-and-secrets-manager-references',
    workerStatusCallbackRequired: true,
    finalizationTableName: 'priority-order-itc-finalization',
    idempotencyStrategy: 'durable-in-flight-marker-before-itc-and-finalization-before-status-callback',
    maxReceiveCount: 3,
    independentPipelineRequired: true,
    apiMustNotRestart: true,
  },
  credentials: [
    {
      key: 'ITC_TEMPLATE_MESSAGE_URL',
      label: 'ITC Template Message URL',
      type: 'url',
      required: true,
      helper: 'Full HTTPS ITC template-message endpoint including the template ID.',
    },
    {
      key: 'ITC_BEARER_TOKEN',
      label: 'ITC Bearer Token',
      type: 'secret',
      required: true,
      masked: true,
      helper: 'ITC bearer token loaded from Secrets Manager or a worker environment reference. Never put it in an SQS job.',
    },
    {
      key: 'ITC_CHANNEL_ID',
      label: 'ITC Channel ID',
      type: 'text',
      required: true,
      helper: 'ITC WhatsApp channel in whatsapp:+<number> format.',
    },
    {
      key: 'PRIORITY_WEB_SDK_URL',
      label: 'Priority Web SDK URL',
      type: 'url',
      required: true,
      helper: 'HTTPS Priority WCF Service.svc URL used by priority-web-sdk.',
    },
    {
      key: 'PRIORITY_WEB_SDK_TABULAINI',
      label: 'Priority tabula.ini',
      type: 'text',
      required: true,
      helper: 'Priority environment ini file; default tabula.ini.',
    },
    {
      key: 'PRIORITY_WEB_SDK_LANGUAGE',
      label: 'Priority Language',
      type: 'number',
      required: true,
      helper: 'Priority language number matching the WWWSHOWORDER sort option.',
    },
    {
      key: 'PRIORITY_WEB_SDK_COMPANY',
      label: 'Priority Company',
      type: 'text',
      required: true,
      helper: 'Priority company/environment code.',
    },
    {
      key: 'PRIORITY_WEB_SDK_APPNAME',
      label: 'Priority App Name',
      type: 'text',
      required: true,
      helper: 'Priority Web SDK application name.',
    },
    {
      key: 'PRIORITY_WEB_SDK_USERNAME',
      label: 'Priority Username',
      type: 'text',
      required: true,
      helper: 'Priority user allowed to run WWWSHOWORDER.',
    },
    {
      key: 'PRIORITY_WEB_SDK_PASSWORD',
      label: 'Priority Password',
      type: 'secret',
      required: true,
      masked: true,
      helper: 'Priority password loaded from an integration-scoped Secrets Manager reference.',
    },
    {
      key: 'PRIORITY_WEB_SDK_DEVICENAME',
      label: 'Priority Device Name',
      type: 'text',
      required: false,
      helper: 'Optional Priority Web SDK device name.',
    },
    {
      key: 'PRIORITY_WEB_SDK_ORDER_SORT_OPTION',
      label: 'Order Sort Option',
      type: 'text',
      required: true,
      helper: 'Desired WWWSHOWORDER Sort choice. The default resolves Priority’s first By Order Number choice even when the session language is not English.',
    },
  ],
  sampleJob: 'fixtures/sample-job.json',
};
