ALTER TABLE "Log" ADD COLUMN "automationId" TEXT;
ALTER TABLE "Log" ADD COLUMN "eventType" TEXT NOT NULL DEFAULT 'automation.log';
ALTER TABLE "Log" ADD COLUMN "schemaVersion" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Log" ADD COLUMN "correlationId" TEXT;
ALTER TABLE "Log" ADD COLUMN "durationMs" INTEGER;
ALTER TABLE "Log" ADD COLUMN "attempt" INTEGER;
ALTER TABLE "Log" ADD COLUMN "statusCode" INTEGER;
