module.exports = {
  name: 'Priority Quote Notification to WhatsApp',
  description: 'Receives a Priority quote webhook and sends a WhatsApp template notification.',
  type: 'webhook',
  manualRun: true,

  connectors: ['priority', 'whatsappCloud'],
  credentialTests: ['priority', 'whatsappCloud'],
  webhook: {
    method: 'POST',
    requiresToken: true,
  },

  logging: {
    direction: 'OUTBOUND',
    reviewRequired: true,
    cloudWatchLogGroup: 'integration-priority-quote-whatsapp',
    steps: [
      'Received from Priority: JSON',
      'Received from Priority: price quotation print URL',
      'Sent to WhatsApp: JSON',
      'Received from WhatsApp: response',
    ],
  },

  testing: {
    allowManualPayload: true,
    allowDryRun: true,
    allowMockOutput: true,
    allowReplay: true,
    defaultMode: 'dry_run',
    modes: ['dry_run', 'test', 'mock_output', 'live'],
    modeDescriptions: {
      dry_run: 'Validates the Priority quote payload, uses a mock Priority print URL, and shows the WhatsApp request summary without sending a message.',
      test: 'Builds the WhatsApp template request with saved credentials and a mock Priority print URL, but does not call Priority or WhatsApp.',
      mock_output: 'Uses a mock Priority print URL and returns a mock WhatsApp response so the flow can be tested without sending a message.',
      live: 'Calls Priority Web SDK to generate the quote print URL, inserts that document URL into the WhatsApp URL button parameter, then sends a real WhatsApp template message through Meta Graph API.',
    },
  },

  credentials: [
    {
      key: 'WHATSAPP_ACCESS_TOKEN',
      label: 'WhatsApp Access Token',
      type: 'secret',
      required: true,
      helper: 'Bearer token for the Meta WhatsApp Cloud API. Stored securely and never displayed after saving.',
      helperUrl: 'https://developers.facebook.com/apps/',
      helperUrlLabel: 'Open Meta app settings',
      placeholder: 'Paste Meta Graph API bearer token',
      validation: { minLength: 20 },
    },
    {
      key: 'WHATSAPP_PHONE_NUMBER_ID',
      label: 'WhatsApp Phone Number ID',
      type: 'text',
      required: true,
      defaultValue: '404655686058819',
      helper: 'Meta phone number ID used in the Graph API messages endpoint.',
      placeholder: '404655686058819',
    },
    {
      key: 'WHATSAPP_TEMPLATE_NAME',
      label: 'Template Name',
      type: 'text',
      required: true,
      defaultValue: 'order_status',
      helper: 'Approved WhatsApp template name in Meta.',
      placeholder: 'order_status',
    },
    {
      key: 'WHATSAPP_LANGUAGE_CODE',
      label: 'Template Language Code',
      type: 'text',
      required: true,
      defaultValue: 'he',
      helper: 'Language code for the approved WhatsApp template.',
      placeholder: 'he',
    },
    {
      key: 'WHATSAPP_GRAPH_API_VERSION',
      label: 'Graph API Version',
      type: 'text',
      required: true,
      defaultValue: 'v25.0',
      helper: 'Meta Graph API version used to build the messages endpoint.',
      placeholder: 'v25.0',
    },
    {
      key: 'WHATSAPP_BUTTON_URL_PREFIX',
      label: 'WhatsApp Button URL Prefix',
      type: 'url',
      required: false,
      defaultValue: 'https://priority.simplyct.co.il/netfiles/',
      helper: 'Static URL prefix configured in the approved WhatsApp template before {{1}}. The integration sends only the generated suffix, usually the Priority .htm filename, as the button parameter.',
      placeholder: 'https://priority.simplyct.co.il/netfiles/',
    },
    {
      key: 'PRIORITY_WEB_SDK_URL',
      label: 'Priority Web SDK URL',
      type: 'url',
      required: true,
      helper: 'Priority WCF Service.svc URL used by the Priority Web SDK to run WWWSHOWCPROF.',
      placeholder: 'https://priority.example.com/wcf/wcf/Service.svc',
    },
    {
      key: 'PRIORITY_WEB_SDK_TABULAINI',
      label: 'Priority tabula.ini',
      type: 'text',
      required: true,
      defaultValue: 'tabula.ini',
      helper: 'Priority environment ini file passed to the Web SDK login request.',
      placeholder: 'tabula.ini',
    },
    {
      key: 'PRIORITY_WEB_SDK_LANGUAGE',
      label: 'Priority Language',
      type: 'number',
      required: true,
      defaultValue: 1,
      helper: 'Priority language number used by the Web SDK session.',
      placeholder: '1',
    },
    {
      key: 'PRIORITY_WEB_SDK_COMPANY',
      label: 'Priority Company',
      type: 'text',
      required: true,
      helper: 'Priority company/environment code for the Web SDK profile.',
      placeholder: 'demo',
    },
    {
      key: 'PRIORITY_WEB_SDK_APPNAME',
      label: 'Priority App Name',
      type: 'text',
      required: true,
      helper: 'Priority Web SDK app name. Use the app name assigned for this integration.',
      placeholder: 'demo',
    },
    {
      key: 'PRIORITY_WEB_SDK_USERNAME',
      label: 'Priority Username',
      type: 'text',
      required: true,
      defaultValue: 'shely.l',
      helper: 'Priority API user allowed to run the WWWSHOWCPROF print procedure.',
      placeholder: 'shely.l',
    },
    {
      key: 'PRIORITY_WEB_SDK_PASSWORD',
      label: 'Priority Password',
      type: 'secret',
      required: true,
      helper: 'Priority Web SDK password. Stored securely and never displayed after saving.',
      placeholder: 'Paste Priority password',
    },
    {
      key: 'PRIORITY_WEB_SDK_DEVICENAME',
      label: 'Priority Device Name',
      type: 'text',
      required: false,
      helper: 'Optional device name for the Priority Web SDK login request. Leave blank if Priority does not require it.',
      placeholder: 'Optional',
    },
  ],

  testPayloads: [
    {
      name: 'Priority quote approved',
      description: 'Priority quote payload that maps ROYY_PHONE to the WhatsApp recipient, CDES to parameter 1, and CPROFNUM to parameter 2.',
      payload: {
        CPROF: {
          CPROFNUM: 'PQ26000001',
          CDES: 'דניאל כהן',
          ROYY_PHONE: '972507573753',
        },
      },
    },
  ],
};
